-- KPGS Frontier Harness v0.1 — Snowflake analytical-copy bootstrap
-- Boundary: EXTERNAL ANALYTICS != LOCAL SOVEREIGN STATE
-- This schema intentionally stores digests/metadata, not semantic input or private payloads.

CREATE DATABASE IF NOT EXISTS KPGS_FRONTIER;
CREATE SCHEMA IF NOT EXISTS KPGS_FRONTIER.EVIDENCE;

CREATE TABLE IF NOT EXISTS KPGS_FRONTIER.EVIDENCE.FRONTIER_TELEMETRY (
    EVENT_SCHEMA STRING NOT NULL,
    REQUEST_ID STRING NOT NULL,
    SOURCE_PROVIDER STRING NOT NULL,
    CAPABILITY STRING NOT NULL,
    SELECTED_PROVIDER STRING NOT NULL,
    OUTPUT_DIGEST STRING NOT NULL,
    DATA_CLASSIFICATION STRING NOT NULL,
    EXTERNAL_PROCESSING_ALLOWED BOOLEAN NOT NULL,
    INGESTED_AT TIMESTAMP_TZ DEFAULT CURRENT_TIMESTAMP()
);

-- Example prepared insert shape. Bind values from the KPGS server-side adapter.
-- INSERT INTO KPGS_FRONTIER.EVIDENCE.FRONTIER_TELEMETRY
--   (EVENT_SCHEMA, REQUEST_ID, SOURCE_PROVIDER, CAPABILITY, SELECTED_PROVIDER,
--    OUTPUT_DIGEST, DATA_CLASSIFICATION, EXTERNAL_PROCESSING_ALLOWED)
-- VALUES (?, ?, ?, ?, ?, ?, ?, ?);
